/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shop_pages;

import javax.swing.JPanel;
import java.awt.*;


/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        plogout = new javax.swing.JPanel();
        lbllogout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pemployee = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ppurchase = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        psupplier = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        phome = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pproducts = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        psale = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pcustomer1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME");
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KHAN SOFT");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MOBILE SHOP MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel4))
                .addContainerGap(531, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 850, 240));

        plogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                plogoutMousePressed(evt);
            }
        });

        lbllogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(45, 118, 232));
        lbllogout.setText("LOGOUT");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop_pages/Images/exit.png"))); // NOI18N

        javax.swing.GroupLayout plogoutLayout = new javax.swing.GroupLayout(plogout);
        plogout.setLayout(plogoutLayout);
        plogoutLayout.setHorizontalGroup(
            plogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plogoutLayout.createSequentialGroup()
                .addGroup(plogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plogoutLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3))
                    .addGroup(plogoutLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lbllogout)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        plogoutLayout.setVerticalGroup(
            plogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plogoutLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbllogout)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(plogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 160, 150));

        pemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pemployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pemployeeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pemployeeMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop_pages/Images/men-age-group-5--v2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 118, 232));
        jLabel2.setText("EMPLOYEE");

        javax.swing.GroupLayout pemployeeLayout = new javax.swing.GroupLayout(pemployee);
        pemployee.setLayout(pemployeeLayout);
        pemployeeLayout.setHorizontalGroup(
            pemployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemployeeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pemployeeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(41, 41, 41))
        );
        pemployeeLayout.setVerticalGroup(
            pemployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(pemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 160, 150));

        ppurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ppurchaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ppurchaseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ppurchaseMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop_pages/Images/return-purchase.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 118, 232));
        jLabel6.setText("PURCHASE");

        javax.swing.GroupLayout ppurchaseLayout = new javax.swing.GroupLayout(ppurchase);
        ppurchase.setLayout(ppurchaseLayout);
        ppurchaseLayout.setHorizontalGroup(
            ppurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppurchaseLayout.createSequentialGroup()
                .addGroup(ppurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppurchaseLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6))
                    .addGroup(ppurchaseLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        ppurchaseLayout.setVerticalGroup(
            ppurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppurchaseLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanel1.add(ppurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 160, 150));

        psupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psupplierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psupplierMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 118, 232));
        jLabel8.setText("SUPPLIER");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop_pages/Images/external-supplier-distribution-xnimrodx-blue-xnimrodx.png"))); // NOI18N

        javax.swing.GroupLayout psupplierLayout = new javax.swing.GroupLayout(psupplier);
        psupplier.setLayout(psupplierLayout);
        psupplierLayout.setHorizontalGroup(
            psupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psupplierLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, psupplierLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(14, 14, 14))
        );
        psupplierLayout.setVerticalGroup(
            psupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(psupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 160, 150));

        phome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                phomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                phomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                phomeMousePressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop_pages/Images/home.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 118, 232));
        jLabel11.setText("HOME");

        javax.swing.GroupLayout phomeLayout = new javax.swing.GroupLayout(phome);
        phome.setLayout(phomeLayout);
        phomeLayout.setHorizontalGroup(
            phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phomeLayout.createSequentialGroup()
                .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(phomeLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel11))
                    .addGroup(phomeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        phomeLayout.setVerticalGroup(
            phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phomeLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jPanel1.add(phome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, 150));

        pproducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pproductsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pproductsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pproductsMousePressed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop_pages/Images/apple-phone.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(45, 118, 232));
        jLabel13.setText("PRODUCTS");

        javax.swing.GroupLayout pproductsLayout = new javax.swing.GroupLayout(pproducts);
        pproducts.setLayout(pproductsLayout);
        pproductsLayout.setHorizontalGroup(
            pproductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pproductsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pproductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pproductsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel13)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pproductsLayout.setVerticalGroup(
            pproductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pproductsLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        jPanel1.add(pproducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 160, 150));

        psale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psaleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psaleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psaleMousePressed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop_pages/Images/experimental-sale-arcade.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(45, 118, 232));
        jLabel15.setText("SALE ITEM");

        javax.swing.GroupLayout psaleLayout = new javax.swing.GroupLayout(psale);
        psale.setLayout(psaleLayout);
        psaleLayout.setHorizontalGroup(
            psaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psaleLayout.createSequentialGroup()
                .addGroup(psaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(psaleLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(psaleLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel15)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        psaleLayout.setVerticalGroup(
            psaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psaleLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        jPanel1.add(psale, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 160, 150));

        pcustomer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pcustomer1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pcustomer1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pcustomer1MousePressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(45, 118, 232));
        jLabel17.setText("CUSTOMER");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop_pages/Images/gender-neutral-user.png"))); // NOI18N

        javax.swing.GroupLayout pcustomer1Layout = new javax.swing.GroupLayout(pcustomer1);
        pcustomer1.setLayout(pcustomer1Layout);
        pcustomer1Layout.setHorizontalGroup(
            pcustomer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcustomer1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel18)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pcustomer1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(45, 45, 45))
        );
        pcustomer1Layout.setVerticalGroup(
            pcustomer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcustomer1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pcustomer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 160, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phomeMouseEntered
        // TODO add your handling code here:
        setColor(phome);
        
    }//GEN-LAST:event_phomeMouseEntered

    private void phomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phomeMouseExited
        // TODO add your handling code here:
        resetColor(phome);
    }//GEN-LAST:event_phomeMouseExited

    private void pemployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemployeeMouseEntered
        // TODO add your handling code here:
        setColor(pemployee);
    }//GEN-LAST:event_pemployeeMouseEntered

    private void pemployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemployeeMouseExited
        // TODO add your handling code here:
        resetColor(pemployee);
    }//GEN-LAST:event_pemployeeMouseExited

    private void psupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psupplierMouseEntered
        // TODO add your handling code here:
        setColor(psupplier);
    }//GEN-LAST:event_psupplierMouseEntered

    private void psupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psupplierMouseExited
        // TODO add your handling code here:
        resetColor(psupplier);
    }//GEN-LAST:event_psupplierMouseExited

    private void plogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plogoutMouseEntered
        // TODO add your handling code here:
        setColor(plogout);
    }//GEN-LAST:event_plogoutMouseEntered

    private void plogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plogoutMouseExited
        // TODO add your handling code here:
        resetColor(plogout);
    }//GEN-LAST:event_plogoutMouseExited

    private void pproductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pproductsMouseEntered
        // TODO add your handling code here:
        setColor(pproducts);
    }//GEN-LAST:event_pproductsMouseEntered

    private void pproductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pproductsMouseExited
        // TODO add your handling code here:
        resetColor(pproducts);
    }//GEN-LAST:event_pproductsMouseExited

    private void psaleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psaleMouseEntered
        // TODO add your handling code here:
        setColor(psale);
    }//GEN-LAST:event_psaleMouseEntered

    private void psaleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psaleMouseExited
        // TODO add your handling code here:
        resetColor(psale);
    }//GEN-LAST:event_psaleMouseExited

    private void ppurchaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppurchaseMouseEntered
        // TODO add your handling code here:
        setColor(ppurchase);
    }//GEN-LAST:event_ppurchaseMouseEntered

    private void ppurchaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppurchaseMouseExited
        // TODO add your handling code here:
        resetColor(ppurchase);
    }//GEN-LAST:event_ppurchaseMouseExited

    private void phomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phomeMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_phomeMousePressed

    private void pemployeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemployeeMousePressed
        // TODO add your handling code here:
         dispose();
        new Employee().show();
    }//GEN-LAST:event_pemployeeMousePressed

    private void psupplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psupplierMousePressed
        // TODO add your handling code here:
           dispose();
        new Supplier().show();
    }//GEN-LAST:event_psupplierMousePressed

    private void plogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plogoutMousePressed
        // TODO add your handling code here:
           dispose();
        new login().show();
    }//GEN-LAST:event_plogoutMousePressed

    private void pproductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pproductsMousePressed
        // TODO add your handling code here:
           dispose();
        new Products().show();
    }//GEN-LAST:event_pproductsMousePressed

    private void psaleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psaleMousePressed
        // TODO add your handling code here:
           dispose();
        new Sales().show();
    }//GEN-LAST:event_psaleMousePressed

    private void ppurchaseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppurchaseMousePressed
        // TODO add your handling code here:
           dispose();
        new Purches().show();
    }//GEN-LAST:event_ppurchaseMousePressed

    private void pcustomer1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcustomer1MouseEntered
        // TODO add your handling code here:
        setColor(pcustomer1);
    }//GEN-LAST:event_pcustomer1MouseEntered

    private void pcustomer1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcustomer1MouseExited
        // TODO add your handling code here:
        resetColor(pcustomer1);
    }//GEN-LAST:event_pcustomer1MouseExited

    private void pcustomer1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcustomer1MousePressed
        // TODO add your handling code here:
        dispose();
        new Customer().show();
    }//GEN-LAST:event_pcustomer1MousePressed

    
    
    
    
    
    
    public void setColor(JPanel panel){
    
    panel.setBackground(new java.awt.Color(115, 163, 239));
    
    }
    
      public void resetColor(JPanel panel){
    
    panel.setBackground(new java.awt.Color(242, 242, 242));
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JPanel pcustomer1;
    private javax.swing.JPanel pemployee;
    private javax.swing.JPanel phome;
    private javax.swing.JPanel plogout;
    private javax.swing.JPanel pproducts;
    private javax.swing.JPanel ppurchase;
    private javax.swing.JPanel psale;
    private javax.swing.JPanel psupplier;
    // End of variables declaration//GEN-END:variables
}
