/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shop_pages;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.ResultSet;
import javax.naming.spi.*;
import javax.swing.JPanel;
import java.awt.*;
import shop_pages.Home;





/**
 * 
 *om
 * @author Admin
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componentResizerUtil1 = new com.k33ptoo.utils.ComponentResizerUtil();
        componentMoverUtil1 = new com.k33ptoo.utils.ComponentMoverUtil();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        btncreateaccount = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        btnlog1 = new com.k33ptoo.components.KButton();
        jLabel4 = new javax.swing.JLabel();
        chkshow = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusername.setBackground(new java.awt.Color(0, 0, 0));
        txtusername.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtusername.setCaretColor(new java.awt.Color(255, 255, 255));
        txtusername.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtusername.setOpaque(true);
        txtusername.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtusernameMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtusernameMousePressed(evt);
            }
        });
        kGradientPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 340, 30));

        txtpassword.setBackground(new java.awt.Color(0, 0, 0));
        txtpassword.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtpassword.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtpassword.setOpaque(true);
        txtpassword.setSelectionColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 340, 30));

        lblusername.setForeground(new java.awt.Color(204, 204, 204));
        lblusername.setText("USER NAME");
        kGradientPanel1.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 80, 20));

        lblpassword.setForeground(new java.awt.Color(204, 204, 204));
        lblpassword.setText("PASSWORD");
        kGradientPanel1.add(lblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        btncreateaccount.setText("CREATE ACCOUNT");
        btncreateaccount.setkBorderRadius(40);
        btncreateaccount.setkEndColor(new java.awt.Color(0, 204, 204));
        btncreateaccount.setkFillButton(false);
        btncreateaccount.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btncreateaccount.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btncreateaccount.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        btncreateaccount.setkSelectedColor(new java.awt.Color(255, 255, 255));
        btncreateaccount.setkStartColor(new java.awt.Color(255, 55, 255));
        btncreateaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateaccountActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btncreateaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OR");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        btnlog1.setText("LOG");
        btnlog1.setkBackGroundColor(new java.awt.Color(255, 51, 255));
        btnlog1.setkBorderRadius(40);
        btnlog1.setkEndColor(new java.awt.Color(0, 204, 204));
        btnlog1.setkFillButton(false);
        btnlog1.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btnlog1.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btnlog1.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        btnlog1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        btnlog1.setkStartColor(new java.awt.Color(255, 0, 255));
        btnlog1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnlog1ItemStateChanged(evt);
            }
        });
        btnlog1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlog1MouseExited(evt);
            }
        });
        btnlog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlog1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnlog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop_pages/L2.jpg"))); // NOI18N
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 170, 160));

        chkshow.setForeground(new java.awt.Color(255, 255, 255));
        chkshow.setText("Show password");
        chkshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkshowActionPerformed(evt);
            }
        });
        kGradientPanel1.add(chkshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 552));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kGradientPanel1KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_kGradientPanel1KeyPressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:
         
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void btnlog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlog1ActionPerformed
        // TODO add your handling code here:
        try{
        if(txtusername.getText().isEmpty()){
        
        JOptionPane.showMessageDialog(null, "Enter the User Name");
       
        return;
        
        
        }
       
       else if(txtpassword.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(null, "Enter the Password");
            return;
        
        }
        else
        {
            String password=txtpassword.getText();
           String id=txtusername.getText();
           
           Connection con=DbConnection.dbconnection();
                  
                 Statement st=con.createStatement();
                 String queary="select * from login where username='"+id+"' and password='"+password+"'";
                  ResultSet rs=st.executeQuery(queary);
                  if(rs.next()){
                  
                  dispose();
                  Home hm=new Home();
                  hm.show();
                  }
                  else{
                  
                   JOptionPane.showMessageDialog(null, "Wrong user name password !!");
                   txtusername.setText("");
                   txtpassword.setText("");
                  
                  }
                 
                 
                
            con.close();
        
        }
       
         
                 
                 

       
      
        
        
        
        
        }catch(Exception ex){
            
            
     
        JOptionPane.showMessageDialog(rootPane, ex.toString());
        }
        
    }//GEN-LAST:event_btnlog1ActionPerformed

    private void txtusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseClicked
        // TODO add your handling code here:
   
    }//GEN-LAST:event_txtusernameMouseClicked

    private void txtusernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtusernameMousePressed

    private void btnlog1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnlog1ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnlog1ItemStateChanged

    private void btnlog1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlog1MouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnlog1MouseExited

    private void chkshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkshowActionPerformed
        // TODO add your handling code here:
        if(chkshow.isSelected()){
        
        txtpassword.setEchoChar((char)0);
        
        }
        else{
          txtpassword.setEchoChar((char)42);
        
        }
        
    }//GEN-LAST:event_chkshowActionPerformed

    private void btncreateaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateaccountActionPerformed
        // TODO add your handling code here:
       
        register rg=new register();
        rg.show();
    }//GEN-LAST:event_btncreateaccountActionPerformed

    private void txtusernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtusernameMouseEntered
 
    
    public void setcolor(JTextField jtextfield){
    
        setBackground(new java.awt.Color(51,51,255));
    
    }
      public void resetcolor(JTextField jtextfield){
    
        setBackground(new java.awt.Color(255,255,255));
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btncreateaccount;
    private com.k33ptoo.components.KButton btnlog1;
    private javax.swing.JCheckBox chkshow;
    private com.k33ptoo.utils.ComponentMoverUtil componentMoverUtil1;
    private com.k33ptoo.utils.ComponentResizerUtil componentResizerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
