/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shop_pages;

import java.awt.Color;
import java.lang.System.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.DriverManager;
import shop_pages.DbConnection;

/**
 *
 * @author Admin
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        lblusername = new javax.swing.JLabel();
        lblusername1 = new javax.swing.JLabel();
        lblusername2 = new javax.swing.JLabel();
        btnregister = new com.k33ptoo.components.KButton();
        txtpassword = new javax.swing.JPasswordField();
        txtcpassword = new javax.swing.JPasswordField();
        chkshow = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop_pages/Images/guest-male.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 120, 120));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CREATE A NEW ACCOUNT");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        txtusername.setBackground(new java.awt.Color(0, 0, 0));
        txtusername.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtusername.setCaretColor(new java.awt.Color(255, 255, 255));
        txtusername.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtusername.setOpaque(true);
        txtusername.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtusernameMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtusernameMousePressed(evt);
            }
        });
        kGradientPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 340, 30));

        lblusername.setForeground(new java.awt.Color(255, 255, 255));
        lblusername.setText("USER NAME");
        kGradientPanel1.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 80, 20));

        lblusername1.setForeground(new java.awt.Color(255, 255, 255));
        lblusername1.setText("PASSWORD");
        kGradientPanel1.add(lblusername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 80, 20));

        lblusername2.setForeground(new java.awt.Color(255, 255, 255));
        lblusername2.setText("CONFIRM PASSWORD");
        kGradientPanel1.add(lblusername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 20));

        btnregister.setText("REGISTER");
        btnregister.setkBackGroundColor(new java.awt.Color(255, 51, 255));
        btnregister.setkBorderRadius(40);
        btnregister.setkEndColor(new java.awt.Color(0, 204, 204));
        btnregister.setkFillButton(false);
        btnregister.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btnregister.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btnregister.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        btnregister.setkSelectedColor(new java.awt.Color(255, 255, 255));
        btnregister.setkStartColor(new java.awt.Color(255, 0, 255));
        btnregister.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnregisterItemStateChanged(evt);
            }
        });
        btnregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnregisterMouseExited(evt);
            }
        });
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        txtpassword.setBackground(new java.awt.Color(0, 0, 0));
        txtpassword.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtpassword.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtpassword.setOpaque(true);
        txtpassword.setSelectionColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 340, 30));

        txtcpassword.setBackground(new java.awt.Color(0, 0, 0));
        txtcpassword.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        txtcpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtcpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtcpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtcpassword.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtcpassword.setOpaque(true);
        txtcpassword.setSelectionColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(txtcpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 340, 30));

        chkshow.setForeground(new java.awt.Color(255, 255, 255));
        chkshow.setText("show password");
        chkshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkshowActionPerformed(evt);
            }
        });
        kGradientPanel1.add(chkshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtusernameMouseClicked

    private void txtusernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtusernameMousePressed

    private void btnregisterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnregisterItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_btnregisterItemStateChanged

    private void btnregisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregisterMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnregisterMouseExited

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
        String username,password;
        
        try{
        if(txtusername.getText().isEmpty()){
        
        JOptionPane.showMessageDialog(null, "Enter the User Name !!");
        return;
        }
        else{
         username=txtusername.getText();
        }
        
         if(txtpassword.getText().isEmpty()){
        
        JOptionPane.showMessageDialog(null, "Enter the User password !!");
        return;
        }
         else{
         
             if(txtcpassword.getText().isEmpty()){
        
        JOptionPane.showMessageDialog(null, "Confirm your  password !!");
        return;
             }
             
             else if(!(txtpassword.getText().equals(txtcpassword.getText()))){
             
              JOptionPane.showMessageDialog(null, "error  !!");
             
             }
             else{
             
                 password=txtcpassword.getText();
                 
                 
                 Connection con=DbConnection.dbconnection();
               
                 
                 Statement st=con.createStatement();
                 String queary="INSERT into login(username,password) VALUES('"+username+"','"+password+"');";
                 int result=st.executeUpdate(queary);
                 if(result>0){
                 
                  JOptionPane.showMessageDialog(null, "YOU ARE SUCCESFULY REGISTERD !!");
                 }
                 else{
                 
                  JOptionPane.showMessageDialog(null, "Cant acces DataBase");
                 }
                 
                 
             
             }
         
         
         }
        
        
        }catch(Exception ex){
        
        
        JOptionPane.showMessageDialog(null, ex.toString());
            System.out.println(ex.toString());
        }
       

    }//GEN-LAST:event_btnregisterActionPerformed

    private void chkshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkshowActionPerformed
        // TODO add your handling code here:
           if(chkshow.isSelected()){
        
        txtpassword.setEchoChar((char)0);
         txtcpassword.setEchoChar((char)0);
        
        }
        else{
          txtpassword.setEchoChar((char)42);
          txtcpassword.setEchoChar((char)42);
        
        }
        
    }//GEN-LAST:event_chkshowActionPerformed

    private void txtusernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseEntered
        // TODO add your handling code here:
        setBackground(Color.yellow);
        
    }//GEN-LAST:event_txtusernameMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnregister;
    private javax.swing.JCheckBox chkshow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblusername;
    private javax.swing.JLabel lblusername1;
    private javax.swing.JLabel lblusername2;
    private javax.swing.JPasswordField txtcpassword;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
